# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from determinant_size import Ui_DetSizeWindow
from multiplication_size import Ui_MultSizeWindow
from inverse_size import Ui_InverseSizeWindow
from solving_size import Ui_SolveSizeWindow
from eigen_choice_screen import Ui_EigenChoiceWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.welcome_message = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setItalic(False)
        font.setUnderline(False)
        self.welcome_message.setFont(font)
        self.welcome_message.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_message.setObjectName("welcome_message")
        self.gridLayout_2.addWidget(self.welcome_message, 0, 0, 1, 2)
        self.multiplication_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.multiplication_button.setFont(font)
        self.multiplication_button.setObjectName("multiplication_button")
        self.multiplication_button.clicked.connect(self.toMultiplication) ################################
        self.gridLayout_2.addWidget(self.multiplication_button, 4, 1, 1, 1)
        self.inverse_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.inverse_button.setFont(font)
        self.inverse_button.setObjectName("inverse_button")
        self.inverse_button.clicked.connect(self.toInverse) ################################
        self.gridLayout_2.addWidget(self.inverse_button, 5, 0, 1, 1)
        self.eigen_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.eigen_button.setFont(font)
        self.eigen_button.setObjectName("eigen_button")
        self.eigen_button.clicked.connect(self.toEigenChoice)
        self.gridLayout_2.addWidget(self.eigen_button, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 2)
        self.main_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.main_info.setFont(font)
        self.main_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_info.setAlignment(QtCore.Qt.AlignCenter)
        self.main_info.setObjectName("main_info")
        self.gridLayout_2.addWidget(self.main_info, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 7, 0, 1, 2)
        self.solving_systems = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.solving_systems.setFont(font)
        self.solving_systems.setObjectName("solving_systems")
        self.solving_systems.clicked.connect(self.toSolve)
        self.gridLayout_2.addWidget(self.solving_systems, 6, 0, 1, 2)
        self.determinant_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setItalic(False)
        font.setUnderline(False)
        self.determinant_button.setFont(font)
        self.determinant_button.setObjectName("determinant_button")
        self.determinant_button.clicked.connect(self.toDeterminant) ################################
        self.gridLayout_2.addWidget(self.determinant_button, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ATLAS"))
        self.welcome_message.setText(_translate("MainWindow", "Welcome to ATLAS!"))
        self.multiplication_button.setText(_translate("MainWindow", "Matrix Multiplication"))
        self.inverse_button.setText(_translate("MainWindow", "Inverse"))
        self.eigen_button.setText(_translate("MainWindow", "Eigenvalues/Eigenvectors"))
        self.main_info.setText(_translate("MainWindow", "Choose an option from the selection below by clicking on the button!"))
        self.solving_systems.setText(_translate("MainWindow", "Solving Systems of Linear Equations"))
        self.determinant_button.setText(_translate("MainWindow", "Determinants"))
    
    def toDeterminant(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DetSizeWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.showMaximized()

    def toMultiplication(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MultSizeWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.showMaximized()
    
    def toInverse(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_InverseSizeWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.showMaximized()

    def toSolve(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SolveSizeWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.showMaximized()

    def toEigenChoice(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_EigenChoiceWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.showMaximized()


if __name__ == "main_screen":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
