# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single_method_choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mult_single_method import Ui_MultSingleWindow
from multiplication import naiveMultiplication, Strassen, getMethods
from emptyimg import empty
from closeWindow import QMainWindow

class Ui_SingleChoiceWindow(object):
    def __init__(self, arg, method):
        self.arg = arg
        self.method = method

    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 831)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setMinimumSize(QtCore.QSize(0, 50))
        self.back_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 3)
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setMinimumSize(QtCore.QSize(125, 50))
        self.submit_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.font = QtGui.QFont()
        self.font.setPointSize(20)
        self.submit_button.setFont(self.font)
        self.submit_button.setObjectName("submit_button")
        self.gridLayout.addWidget(self.submit_button, 7, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.methods_info = QtWidgets.QLabel(self.centralwidget)
        self.methods_info.setFont(self.font)
        self.methods_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.methods_info.setAlignment(QtCore.Qt.AlignCenter)
        self.methods_info.setWordWrap(True)
        self.methods_info.setObjectName("methods_info")
        self.gridLayout.addWidget(self.methods_info, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 1)
        self.method_store = QtWidgets.QScrollArea(self.centralwidget)
        self.method_store.setWidgetResizable(True)
        self.method_store.setObjectName("method_store")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 358, 201))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.method_store.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.method_store, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        if self.method == "mult":
            self.mult()
            self.submit_button.clicked.connect(self.multCall)
        elif self.method == "det":
            pass
        elif self.method == "solve":
            pass
        elif self.method == "inverse":
            pass
        elif self.method == "e_val":
            pass
        elif self.method == "e_vec":
            pass

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_button.setText(_translate("MainWindow", "Go Back"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.methods_info.setText(_translate("MainWindow", "Select one of the methods below:"))

    def mult(self):
        self.standard = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.standard.setObjectName("standard")
        self.verticalLayout.addWidget(self.standard)
        self.standard.setText("Standard Method")
        self.standard.setFont(self.font)

        self.strassen = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.strassen.setObjectName("strassen")
        self.verticalLayout.addWidget(self.strassen)
        self.strassen.setText("Strassen's Method")
        self.strassen.setFont(self.font)

        # self.one = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.one.setObjectName("one")
        # self.verticalLayout.addWidget(self.one)
        # self.one.setText("Strassen's Method")
        # self.one.setFont(self.font)

        # self.two = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.two.setObjectName("two")
        # self.verticalLayout.addWidget(self.two)
        # self.two.setText("Strassen's Method")
        # self.two.setFont(self.font)

        # self.three = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.three.setObjectName("three")
        # self.verticalLayout.addWidget(self.three)
        # self.three.setText("Strassen's Method")
        # self.three.setFont(self.font)

        # self.four = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.four.setObjectName("four")
        # self.verticalLayout.addWidget(self.four)
        # self.four.setText("Strassen's Method")
        # self.four.setFont(self.font)

        # self.five = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.five.setObjectName("five")
        # self.verticalLayout.addWidget(self.five)
        # self.five.setText("Strassen's Method")
        # self.five.setFont(self.font)

        # self.six = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.six.setObjectName("six")
        # self.verticalLayout.addWidget(self.six)
        # self.six.setText("Strassen's Method")
        # self.six.setFont(self.font)

        # self.seven = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.seven.setObjectName("seven")
        # self.verticalLayout.addWidget(self.seven)
        # self.seven.setText("Strassen's Method")
        # self.seven.setFont(self.font)

        # self.eight = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.eight.setObjectName("eight")
        # self.verticalLayout.addWidget(self.eight)
        # self.eight.setText("Strassen's Method")
        # self.eight.setFont(self.font)

        # self.nine = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.nine.setObjectName("nine")
        # self.verticalLayout.addWidget(self.nine)
        # self.nine.setText("Strassen's Method")
        # self.nine.setFont(self.font)

        # self.ten = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        # self.ten.setObjectName("ten")
        # self.verticalLayout.addWidget(self.ten)
        # self.ten.setText("Strassen's Method")
        # self.ten.setFont(self.font)

    def multCall(self):
        if self.standard.isChecked() == True:
            mult = naiveMultiplication(*self.arg)
            empty()
            mult.calc()
            mult.latex2img()
        elif self.strassen.isChecked() == True:
            empty()
            mult = Strassen(*self.arg)
            mult.calc()
            mult.latex2img()

        self.window = QMainWindow()
        self.ui = Ui_MultSingleWindow()
        self.ui.setupUi(self.window)
        self.MainWindow.hide()
        self.window.showMaximized()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_SingleChoiceWindow(None, None)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
